In [ ]:
#Importar la librería
import numpy as np

In [ ]:
#Crear arreglos
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [ ]:
#Asignar un arreglo a una variable y seleccionar el  índice 4 
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

In [ ]:
#Conocer el tipo de dato
type(a[2])

numpy.int64

In [ ]:
#Seleccionar el índice 3 hacia adelante
a[3:]

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [ ]:
#Seleccionar desde el índice 3 hasta el índice 7
a[3:7]

array([ 4, 30, 51,  7])

In [ ]:
#Seleccionar desde el índice 1 cada 4 índices
a[1::4]

array([30, 51, 40])

In [ ]:
#Crear un arreglo de ceros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#Crear un arreglo de unos de dos dimensiones 
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Crear un arreglo de dos dimensiones
b = np.array( [['x', 'y', 'z'], ['a', 'c', 'e']])
print(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


In [ ]:
#Conocer el número de dimensiones
b.ndim

2

In [ ]:
#Ordenar de menor a mayor 
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [ ]:
cabeceras = [ ('nombre', 'S10' ), ('edad', int) ]
datos = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15) ]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad' )

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

In [ ]:
#Crear un arreglo dinámico de 25 elementos
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#Crear un arreglo dinámico con un límite inferior y un límite superior
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#Crear un arreglo dinámico con un límite inferior y un límite superior e incremento de 5
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#Crear un arreglo bidimensional de 3 filas y 5 columnas y el único valor 10

np.full( ( 3, 5 ), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
#Crear un diagonal de arreglo tipo bidimensional
np.diag ( [0, 3, 9, 10] )

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [ ]:
#Operaciones sobre arreglos
# Aritmética
a = np.arange(4)

print("a     =", a)
print("a + 5 =", a + 5)
print("a - 5 =", a - 5)
print("a * 2 =", a * 2)
print("a / 2 =", a / 2)
print("a // 2 =", a // 2)  
print("-a     = ", -a)
print("a ** 2 = ", a ** 2)
print("a % 2  = ", a % 2)

a     = [0 1 2 3]
a + 5 = [5 6 7 8]
a - 5 = [-5 -4 -3 -2]
a * 2 = [0 2 4 6]
a / 2 = [0.  0.5 1.  1.5]
a // 2 = [0 0 1 1]
-a     =  [ 0 -1 -2 -3]
a ** 2 =  [0 1 4 9]
a % 2  =  [0 1 0 1]


In [ ]:
#Estadística
a = np.arange(10)

print(np.mean(a))           # media (promedio)
print(np.median(a))         # mediana 
print(np.var(a))            # varianza
print(np.std(a))            # desviación estándar

4.5
4.5
8.25
2.8722813232690143


In [ ]:
a=np.array([1,8,7,9,5])
print("Media:",np.mean(a))
print("Mediana",np.median(a))


Media: 6.0
Mediana 7.0


In [ ]:

# Numpy no puede obtener la moda
from scipy import stats as st

edades = [21, 17, 89, 76, 32, 21, 45, 21, 89, 21, 15, 89, 21]

moda=st.mode(edades)

display(moda)

ModeResult(mode=array([21]), count=array([5]))